server {
    listen 80;
    
    location /api/auth/ {
        proxy_pass http://auth-service/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    location /api/competitions/ {
        proxy_pass http://competition-service/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /monitoring/prometheus/ {
        proxy_pass https://prometheus:9090
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /monitoring/grafana/ {
        proxy_pass https://grafana:9090
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/auth {
        return 301 /api/auth/;
    }
    
    location /api/competitions {
        return 301 /api/competitions/;
    }

    location /monitoring/prometheus {
        return 301 /monitoring/prometheus/;
    }

    location /monitoring/grafana {
        return 301 /monitoring/grafana/;
    }
    
    location /health {
        return 200 'Gateway OK';
        add_header Content-Type text/plain;
    }
    
    location / {
        return 404 'Not Found';
    }
}