events {
    worker_connections 1024;
}

http {
    # Add Docker's internal DNS resolver
    resolver 127.0.0.11 valid=10s;
    
    upstream auth-service {
        server auth-service:8080;
    }

    upstream competition-service {
        server competition-service:8080;
    }

    upstream notification-service {
        server notification-service:8080;
    }

    upstream user-service {
        server user-service:8080;
    }

    include /etc/nginx/conf.d/*.conf;
}