events {
    worker_connections 1024;
}

http {
    upstream auth-service {
        server auth-service:8080;
    }

    upstream competition-service {
        server competition-service:8080;
    }

    include /etc/nginx/conf.d/*.conf;
}