services:

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: ciblorgasport-api-gateway
    ports:
      - "80:80"
    depends_on:
      auth-service:
        condition: service_started
      competition-service:
        condition: service_started
    networks:
      - ciblorgasport

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile        # renomme ton Dockerfile actuel en Dockerfile-auth
    container_name: ciblorgasport-auth
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/glop
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ciblorgasport

  competition-service:
    build:
      context: .
      dockerfile: competition-service/Dockerfile
    container_name: ciblorgasport-competition
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/glop
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ciblorgasport

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ciblorgasport
    ports:
      - 9090:9090
  
  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/datasources:/etc/grafana/provisioning/datasources

  db:
    image: postgres:16.10-bookworm
    environment:
      POSTGRES_DB: glop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d glop"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ciblorgasport

volumes:
  postgres_data:

networks:
  ciblorgasport:
    driver: bridge