services:

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:80"
    depends_on:
      auth-service:
        condition: service_started
      user-service:
        condition: service_started
      competition-service:
        condition: service_started
      notification-service:
        condition: service_started
      kafka:
        condition: service_started
      prometheus:
        condition: service_started
      grafana:
        condition: service_started
      db:
        condition: service_healthy
    networks:
      - ciblorgasport

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: ciblorgasport-auth
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/glop
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      NOTIFICATION_BASE_URL: http://notification-service:8080
      NOTIFICATION_INCIDENT_GROUP_NAME: Incidents
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ciblorgasport
  

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: ciblorgasport-user
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/glop
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ciblorgasport

  competition-service:
    build:
      context: .
      dockerfile: competition-service/Dockerfile
    container_name: ciblorgasport-competition
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/glop
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ciblorgasport

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: ciblorgasport-notification
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/glop
      DATASOURCE_USERNAME: admin
      DATASOURCE_PASSWORD: password
      KAFKA_URL: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      INCIDENT_GROUP_NAME: Incidents
    depends_on:
      kafka:
        condition: service_started
      auth-service:
        condition: service_started
      competition-service:
        condition: service_started
    networks:
      - ciblorgasport

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"  # Host port
      - "9093:9093"  # Docker network port
    environment:
      KAFKA_NODE_ID: 1
      # Define listeners
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      # Advertised listeners - THIS IS KEY
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,HOST:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    networks:
      - ciblorgasport

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alerts.yml:/etc/prometheus/alerts.yml
    networks:
      - ciblorgasport
    ports:
      - 9090:9090
    depends_on:
      auth-service:
        condition: service_started
      user-service:
        condition: service_started
      competition-service:
        condition: service_started
      notification-service:
        condition: service_started
      nginx-exporter:
        condition: service_started

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.3.0
    container_name: nginx-exporter
    command:
      - --nginx.scrape-uri=http://api-gateway/nginx_status
    networks:
      - ciblorgasport
  
  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    networks:
      - ciblorgasport
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/dashboards/provisioning:/etc/grafana/provisioning/dashboards
      - ./monitoring/dashboards/json:/var/lib/grafana/dashboards
    depends_on:
      prometheus:
        condition: service_started

  db:
    image: postgres:16.10-bookworm
    environment:
      POSTGRES_DB: glop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d glop"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ciblorgasport

volumes:
  postgres_data:

networks:
  ciblorgasport:
    driver: bridge
